# Generated by Django 3.1.3 on 2020-11-17 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('woobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicereading',
            name='date_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='devicereading',
            name='ph',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='devicereading',
            name='temp',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
    ]
