# Generated by Django 3.1.3 on 2020-11-17 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('woobs', '0002_auto_20201117_1540'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicereading',
            name='device_id',
            field=models.CharField(default='N/A', max_length=255),
            preserve_default=False,
        ),
    ]
